version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped

  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpass
  #     MYSQL_DATABASE: daleely_schema_new
  #     MYSQL_USER: daleely_demo_example
  #     MYSQL_PASSWORD: 1234
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   networks:
  #     default:
  #       aliases:
  #         - localhost 

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "7000:7000"
    depends_on:
      - qdrant
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 7000 --reload
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default

# volumes:
#   mysql_data:

networks:
  default:
    name: daleey_ai_network